# Generated by Django 4.1.7 on 2023-02-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likes',
            field=models.IntegerField(default=1),
        ),
    ]
